# Content for both languages. Edit here, then run: python3 build.py
T = {
"en": dict(
  lang="en", url=SITE, prefix="",
  title="Dr. Sebastian Schoenen – AI for Insurance Claims | ControlExpert & Solvd Group",
  description="Dr. Sebastian Schoenen: AI executive for insurance claims. Director Innovation & Technology at ControlExpert, Head of Data & AI CoE at Solvd Group, leading 75+ data & AI specialists.",
  og_title="Dr. Sebastian Schoenen – AI for Insurance Claims",
  og_desc="Director of Innovation & Technology, ControlExpert · Head of Data & AI Center of Excellence, Solvd Group. Agentic AI, computer vision and GenAI for motor claims & repair.",
  nav=[("#about","About"),("#experience","Experience"),("#skills","Skills"),("#projects","Innovation"),("#talks","Talks"),("#volunteer","Community"),("#contact","Contact")],
  hero_tag="#AI4Claims · Cologne/Bonn region · Germany",
  hero_title="Director of Innovation &amp; Technology at ControlExpert GmbH · Head of Data &amp; AI Center of Excellence at Solvd Group",
  hero_quote="Own the brain. Rent the body.",
  hero_badges=["Agentic AI","Computer Vision","Generative AI","InsurTech","Physics PhD"],
  btn_pri="Projects & research", btn_sec="Get in touch",
  hero_stats=[("173+","Publications"),("25.5k","Citations"),("6","Patents"),("75+","Data &amp; AI specialists led")],
  photo_alt="Portrait of Dr. Sebastian Schoenen",
  about_label="About", about_title="AI leadership. <span>From strategy to production.</span>",
  about_p=[
    "I lead the Data &amp; AI Center of Excellence of Solvd Group, the claims and repair management group serving <strong>more than 200 customers</strong> from insurance, leasing and fleet companies in <strong>46 countries</strong>, and I am Director of Innovation &amp; Technology at ControlExpert GmbH. The mandate covers innovation and the group's Data &amp; AI product portfolio: an organisation of <strong>75+ data and AI specialists</strong> in agentic AI, computer vision, generative AI and NLP, with budget ownership for the portfolio.",
    "The vision we work towards is simple: drivers anywhere get their claim settled fairly on the same day. The Center of Excellence is the technological engine behind it. We build approaches beyond what current solutions can do and turn them into customer value. ClaimsPilot, our agentic claims platform, is the most visible result so far.",
    "As overall business owner for data and AI products I own the decisions that determine whether that happens at scale: research and innovation strategy, make-or-buy for AI products (own the brain, rent the body: the differentiating intelligence is ours, the infrastructure is rented), the IP strategy behind six patents, MLOps, and the operating model of the CoE. Platform and cloud strategy sit with IT; I am their key stakeholder and align them with the product strategy. AI governance is defined centrally by the Chief Data Officer and implemented by me: responsible-AI rules, EU AI Act requirements and model risk management for AI that decides on real claims.",
    "Research stays part of the job, through an active network of universities and institutes. Before moving into industry I was a researcher at RWTH Aachen myself, with a Ph.D. in astroparticle physics. It still shapes how I lead: measure first, then decide.",
  ],
  about_cards=[
    ("phd","Ph.D. in Physics","RWTH Aachen University · Astroparticle physics · 2012–2017"),
    ("msc","M.Sc. in Physics","RWTH Aachen University · High-energy particle and astroparticle physics · 2010–2012"),
    ("work","ControlExpert GmbH / Solvd Group","Langenfeld (Rheinland) · since 2018"),
    ("net","Research network","RWTH Aachen · TU Berlin · Bergische Universität Wuppertal · Ruhr-Universität Bochum · TU Dortmund · Fraunhofer · DFKI and others"),
    ("pin","Location","Cologne/Bonn region, Germany"),
    ("lang","Languages","German (native) · English (fluent)"),
    ("li","LinkedIn",f'<a href="{LINKEDIN}" target="_blank" rel="noopener">View profile</a>'),
  ],
  exp_label="Work experience", exp_title="Career <span>path</span>",
  exp=[
    ("Apr 2025 – Present","Head of Data & AI Center of Excellence","Solvd Group · Hybrid",
     "Built and lead the group's Data &amp; AI Center of Excellence: 75+ data and AI specialists across agentic AI, computer vision, GenAI and NLP, for a group serving 200+ insurance, leasing and fleet customers in 46 countries. Overall business owner for data and AI products: product portfolio and budget, research and innovation strategy, make-or-buy and IP decisions, MLOps and the CoE operating model, plus implementation of the group's AI governance. Accountable for ClaimsPilot, the group's agentic claims platform, from strategy to production.",
     ["Product portfolio","Organisation building","Budget ownership","AI governance"]),
    ("Apr 2023 – Present","Director of Innovation & Technology","ControlExpert GmbH · On-site",
     "Own the research and innovation strategy for AI at a company handling around 20 million claims per year. Decide on make-or-buy for core AI capabilities, steer the R&amp;D pipeline and the IP strategy behind six patents, act as key stakeholder for IT's platform and cloud strategy, and drive publicly funded research with partners such as RWTH Aachen, Fraunhofer and Bergische Universität Wuppertal.",
     ["Research &amp; innovation strategy","Make-or-buy","IP strategy","Public research funding"]),
    ("Oct 2020 – Mar 2025","Head of Research & Development","ControlExpert GmbH",
     "Led the R&amp;D department and scaled AI research into production. Peer-reviewed publications, patents and applied research in computer vision and uncertainty quantification for motor claims.",
     ["Deep learning","Computer vision","Research management"]),
    ("Apr 2019 – Jun 2023","Product Manager AI Services","ControlExpert GmbH",
     "Managed the AI product portfolio and connected research with market needs. Shaped the product strategy for AI-driven claims automation services.",
     ["AI product management","Claims automation"]),
    ("Apr 2019 – Oct 2020","Team Leader Research and Development","ControlExpert GmbH",
     "Built and led the R&amp;D team that grew into the later R&amp;D department, combining applied deep learning with claims domain expertise.",
     ["Team leadership","Applied research"]),
    ("Oct 2018 – Apr 2019","Team Leader AI Image Recognition","ControlExpert GmbH",
     "Led a data science team developing deep neural networks for vehicle damage recognition, while continuing hands-on data science work.",
     ["CNNs","Image recognition","Team leadership"]),
    ("Feb 2018 – Sep 2018","Data Scientist","ControlExpert GmbH",
     "Applied machine learning to insurance claims data and laid the groundwork for automated damage assessment pipelines.",
     ["Machine learning","Data analytics"]),
    ("Feb 2017 – Jan 2018","Data Scientist","umlaut (formerly P3 Group) · Aachen region",
     "Data science in an industrial consulting setting after completing the doctorate.",
     ["Data science","Consulting"]),
    ("Oct 2012 – Jan 2017","Research Associate (PhD student)","RWTH Aachen University · III. Physikalisches Institut B",
     "Doctoral research in astroparticle physics. Developed statistical and machine learning methods for high-energy physics data analysis.",
     ["Astroparticle physics","Statistical modelling","Academic research"]),
  ],
  skills_label="Skills", skills_title="Core <span>expertise</span>",
  skills=[
    ("Executive leadership",["Research &amp; innovation strategy","Data &amp; AI product portfolio","Organisation building","Budget ownership","Make-or-buy strategy","IP strategy","AI governance implementation / EU AI Act","Board &amp; stakeholder communication"]),
    ("AI &amp; machine learning",["Agentic AI","Generative AI","Deep learning","Computer vision","NLP / NLU","Predictive modelling","Neural architecture search","MLOps"]),
    ("Domain expertise",["Claims management","InsurTech","Repair management","Product-led AI","Claims automation","Fraud detection","Damage assessment","Motor insurance"]),
    ("Research &amp; methods",["R&amp;D management","Academic publishing","Data analytics","Mathematics","Astroparticle physics","Patent development","Uncertainty quantification"]),
  ],
  proj_label="Portfolio", proj_title="Impact &amp; <span>innovation</span>",
  impact=[("10","AI products"),("6","Patents filed / granted"),("10","Funded research projects"),("173+","Publications · 25.5k citations")],
  tabs=[("products","Products","10"),("patents","Patents","6"),("research","Research","10"),("publications","Publications","173+"),("awards","Awards","5")],
  flagship="Flagship product", ai_product="AI product",
  products=[
    ("ClaimsPilot – agentic AI for end-to-end motor claims",
     "Production multi-agent platform orchestrating the full motor claims journey: multilingual intake via voice, online, document and e-mail, automated damage and cost assessment using repair, OEM and policy data, through to settlement and customer communication. Built on AWS. Winner of the AI Communication Award 2026.",
     "Solvd Group / ControlExpert", True),
    ("Claims Advisor","Real-time next-best-action system embedded in the FNOL process. Analyses submitted damage photos and claim context to recommend the handling path: repair, replacement or total loss.","ControlExpert GmbH", False),
    ("AI Damage Assessment – image &amp; telematics","Combines deep learning on damage images with telematics sensor data for severity scoring, part-level repair/replace decisions and cost estimation. The backbone of touchless claims processing.","ControlExpert GmbH", False),
    ("AI Cost Assessment","ML model for automated repair cost estimation based on damage assessment outputs. Data-driven cost benchmarks at scale, less manual review, better cost containment.","ControlExpert GmbH", False),
    ("Image Fraud Prevention","AI image analysis detecting manipulated, AI-generated or reused damage photos in the claims process. Finds patterns invisible to human reviewers in high-volume portfolios.","ControlExpert GmbH", False),
    ("FraudGuard AI","Hybrid fraud detection combining rule-based logic with a custom AI model to flag suspicious claim patterns across document and image checks.","ControlExpert GmbH", False),
    ("KI InvoiceCheck","Automated invoice auditing for motor claims. Validates repair invoices against damage assessments, labour rates and parts pricing to catch overbilling and inconsistencies.","ControlExpert GmbH", False),
    ("Intelligent Document Processing","End-to-end AI pipeline extracting, classifying and structuring information from unstructured claims documents such as repair invoices, police reports and medical certificates.","ControlExpert GmbH", False),
    ("Voicebot for FNOL","Conversational AI for fully automated first notification of loss. Guides claimants through damage reporting, captures structured data and triggers claims workflows.","ControlExpert GmbH", False),
    ("GenAI-based liability &amp; coverage check","Generative AI analysing policy documents, accident reports and claim facts to assess liability and coverage. Cuts manual legal review and speeds up complex cases.","ControlExpert GmbH / Solvd Group", False),
  ],
  patents=[
    ("US · EP · JP · DE","Method for assessing damage to a motor vehicle","AI-based method for evaluating vehicle damage from image files: detecting damage per vehicle zone, determining severity and deciding for each part whether repair or replacement is required.","US11397972B2 · EP3736758A1 · Priority 2019-03-05 · Granted 2022-07-26"),
    ("DE","Automatic detection of vehicle damage in an accident","Sensor-based detection using continuously acquired acceleration, speed and yaw-rate values while driving to identify damage events automatically.","DE102019105535A1 · Priority 2019-03-05"),
    ("DE","Automatic detection of damage events from image material","Neural network generating multiple weighted bounding boxes, building a 2D density function from them and using it to localise and classify damage, overcoming the limits of non-maximum suppression.","DE102019129826A1 · DE102019129826B4 · Priority 2019-11-05 · Granted 2025-01-23"),
    ("DE","Plausibility of a vehicle repair plan","Method for checking a vehicle repair plan for technical plausibility, evaluating which parts require repair or replacement.","DE102020105545A1 · Priority 2020-03-02"),
    ("DE","Method for extracting a vehicle identification number","AI-based extraction of a VIN from an image of a vehicle registration document or the vehicle itself, enabling automated vehicle identification in claims workflows.","DE102019109941A1 · Priority 2019-04-15"),
    ("DE","Simple annotation of complex damage on image material","Neural-network-based method for annotating complex damage on images, simplifying the creation of training data for AI damage assessment.","DE102019129968A1 · Priority 2019-11-06"),
  ],
  ongoing="Ongoing", completed="Completed", upcoming="Upcoming",
  research=[
    ("BMFTR · ErUM-Data","ErUM-ARIA",
     "Efficient AI methods for physical simulations, developed jointly by RWTH Aachen University, FAU Erlangen-Nürnberg and ControlExpert. The partners bring simulation problems from astroparticle physics, particle physics, engineering and digital claims handling.",
     "BMFTR · RWTH Aachen · FAU Erlangen-Nürnberg","since 2026","ongoing"),
    ("EFRE / JFT NRW","PocketViz",
     "Mobile AI app for detecting and measuring surface defects from multimodal data (image, depth, text). ControlExpert's use case: dents and scratches on vehicle bodies. Led by the TMDT institute at Bergische Universität Wuppertal, with Dermanostic and Schorn as further application partners.",
     "Bergische Universität Wuppertal · EFRE/JFT NRW 2021–2027","","ongoing"),
    ("EFRE / NRW","Just Scan It 3D",
     "AI workflow converting smartphone captures into precise 3D meshes and Gaussian splats for virtual damage assessment and AR-based claims inspection.",
     "EFRE / NRW Ministry of Economic Affairs","since summer 2024","ongoing"),
    ("Gaia-X · BMWK","OpenGPT-X",
     "Consortium building large open language models in the Gaia-X ecosystem, with ControlExpert as the insurance industry partner alongside Fraunhofer, Aleph Alpha, DFKI, Forschungszentrum Jülich, IONOS, TU Dresden and WDR. Findings presented at the openGPT-X &amp; appliedAI conference 2023.",
     "Fraunhofer IAIS / IIS (lead) · BMWK","2022–2024","done"),
    ("BMBF","FedXtract",
     "Open-source SDK for federated learning so that companies can train AI models for document extraction jointly without sharing raw data, then adapt them via transfer learning. ControlExpert contributed the claims document use case and labelled data.",
     '<a href="https://www.fedxtract.net/" target="_blank" rel="noopener">fedxtract.net</a> · Condat AG (coord.) · Fraunhofer IAIS · FKZ 01IS21037A',"11/2021 – 04/2024","done"),
    ("Gaia-X · BMWK","Autowerkstatt 4.0",
     "Winner project of the federal Gaia-X funding competition: an AI-based vehicle diagnostics ecosystem connecting workshops, diagnostic system providers and AI companies via Gaia-X federated services.",
     "eco – Verband der Internetwirtschaft (lead) · BMWK","","done"),
    ("BMWK","PlanQK",
     "Platform and ecosystem for quantum-assisted AI. ControlExpert joined as associated partner in 2021 to explore where quantum-supported AI could help motor claims management.",
     "StoneOne AG (lead) · BMWK","since 2021","done"),
    ("BMBF","HUMAINE – Human-Centered AI Competence Center",
     "Competence center for the Ruhr metropolitan region developing methods at the interface of AI development, validation and human-centred work organisation in industry and SMEs.",
     "BMBF / PTKA · Funding code 02L19C200","","done"),
    ("EFRE / NRW","BIT – Bergische Innovationsplattform für KI",
     "EU- and NRW-funded AI transfer platform at Bergische Universität Wuppertal. ControlExpert contributed applied R&amp;D linking academic AI research with automotive and insurance use cases.",
     "Bergische Universität Wuppertal / EFRE NRW","","done"),
    ("NRW","IT'S DIGITIVE – Secure digital order processing for 3D printing",
     "NRW-funded project developing a spare-parts supply ecosystem for the automotive industry with secure digital order processing for productive use of 3D printing.",
     "State of North Rhine-Westphalia","","done"),
  ],
  pub_groups=[
   ("Applied AI &amp; industry",[
    ("Springer · May 2024","Uncertainty estimates for semantic segmentation: providing enhanced reliability for automated motor claims handling","Meta-classification model assessing the precision of segments predicted for car body parts under adverse photo conditions. AUROC 0.915; removing low-quality segments lifts mean IoU by 16 pp and cuts wrongly predicted segments by 77 %.","Machine Vision and Applications · Küchler, Kröll, Schoenen, Witte"),
    ("Springer · Sep 2024","ResBuilder: Automated learning of depth with residual structures","Neural architecture search that builds ResNet architectures from scratch at near state-of-the-art accuracy with lower compute. Default parameters tuned once on CIFAR-10 generalise to a proprietary fraud detection dataset.","ICANN 2024 · <a href=\"https://arxiv.org/abs/2308.08504\" target=\"_blank\" rel=\"noopener\">arXiv:2308.08504</a>"),
    ("IEEE/CVF WACV · Dec 2023","Identifying label errors in object detection datasets by loss inspection","First benchmark for label error detection in object detection plus a loss-based detection method that outperforms all baselines. Finds real label errors on public test sets (precision up to 71.5 %) and on a proprietary dataset (97 %).","Winter Conference on Applications of Computer Vision (WACV 2024)"),
    ("SIU Today · Apr 2024","Image Fraud Prevention: Enhancing security and efficiency with image recognition for claims automation","Practitioner article on how computer vision automates repair cost determination and, at the same time, embeds real-time fraud prevention into claims handling, and what it takes to deploy this across the damage value chain.","SIU Today – Update on Insurance Fraud"),
    ("VVW · Apr 2023","Innovatives Schadenmanagement – Wie Technologie die Wertschöpfungskette bei Versicherungsunternehmen revolutioniert","Book chapter on technology-driven transformation of the insurance claims value chain.","In: Insurance &amp; Innovation 2023 (ed. Andreas Eckstein) · Verlag Versicherungswirtschaft, Karlsruhe"),
    ("J. Design Research · Dec 2022","Identification of similar design principles of passenger cars using deep neural networks","A network trained to classify car brands from images is repurposed, via systematic error analysis, to identify car models that follow similar design principles across manufacturers.","Journal of Design Research, Vol. 20, No. 2"),
    ("IEEE ITSC · Oct 2021","Fully automated, realistic license plate substitution in real-life images","CycleGAN-based system replacing licence plates in image crops with customised patterns while preserving pose, lighting and sharpness, trained without labels. Validated via plate-recognition experiments, a human acceptance study and FID.","Intelligent Transportation Systems Conference, Indianapolis"),
   ]),
   ("Physics – IceCube Neutrino Observatory",[
    ("Dissertation · Jul 2017","Discovery and characterization of a diffuse astrophysical muon neutrino flux with the IceCube Neutrino Observatory","Doctoral thesis, RWTH Aachen University, III. Physikalisches Institut B.","<a href=\"https://publications.rwth-aachen.de/record/696221\" target=\"_blank\" rel=\"noopener\">publications.rwth-aachen.de</a>"),
    ("Astrophysical Journal · Dec 2016","Observation and characterization of a cosmic muon neutrino flux from the Northern Hemisphere using six years of IceCube data","Excludes a purely atmospheric origin of the highest-energy muon neutrino events at 5.6σ and characterises the astrophysical flux with a hard spectral index of 2.13 ± 0.13; the highest-energy event has a reconstructed muon energy of 4.5 PeV.","The Astrophysical Journal, Vol. 833, No. 1 · IceCube Collaboration"),
    ("Science · Jul 2018","Multimessenger observations of a flaring blazar coincident with high-energy neutrino IceCube-170922A","First identification of a likely source of high-energy cosmic neutrinos: the IceCube event of 22 September 2017 coincided with a gamma-ray flare of the blazar TXS 0506+056, observed by 18 telescopes across the electromagnetic spectrum.","Science, Vol. 361, eaat1378 · IceCube, Fermi-LAT, MAGIC et al."),
    ("Nature · Nov 2017","Measurement of the multi-TeV neutrino interaction cross-section with IceCube using Earth absorption","First measurement of the neutrino–nucleon cross-section at energies of 6.3–980 TeV, far beyond accelerator reach, using the Earth itself as the target and the absorption of upgoing neutrinos as the observable.","Nature 551, 596–600 · IceCube Collaboration"),
    ("Nature Physics · Sep 2018","Neutrino interferometry for high-precision tests of Lorentz symmetry with IceCube","Atmospheric neutrinos travelling through the Earth act as an interferometer for spacetime symmetry. The analysis sets some of the most stringent limits on Lorentz violation in the neutrino sector to date.","Nature Physics 14, 961–966 · IceCube Collaboration"),
    ("Eur. Phys. J. C · Jul 2014","Search for non-relativistic magnetic monopoles with IceCube","Search for GUT-era magnetic monopoles via nucleon-decay catalysis. No signal observed; flux limits improved by one to two orders of magnitude, three orders below the Parker bound.","Eur. Phys. J. C 74:2938 · IceCube Collaboration"),
   ]),
  ],
  pub_note=f'Selection. 173 publications and 25,504 citations in total, most of them as author within the IceCube Collaboration · <a href="{RESEARCHGATE}" target="_blank" rel="noopener">Full list on ResearchGate</a>',
  awards=[
    ("Industry award · 2026","AI Communication Award 2026 – Winner","ClaimsPilot won the category “AI Strategy, Analytics &amp; Agents in Communication”. The independent jury from academia and industry recognised the agentic platform for orchestrating the motor claims journey from first notification to settlement. I accepted the award on behalf of the team.","AI Communication Award / ZIEHL-ABEGG SE · July 2026"),
    ("Industry award · 2024","KI Innovation Award 2024 – Heavyweight category","Awarded by F.A.Z. Institut and KI Bundesverband at the “Innovative Leaders” conference for ControlExpert's AI-driven claims and repair management process.","F.A.Z. Institut · KI Bundesverband · July 2024"),
    ("Hackathon · 3rd place","Talanx Insurance Hackathon","Third place at the Talanx Insurance Hackathon for applied AI in insurance.","Talanx · April 2018 · <a href=\"https://www.hackitover.com\" target=\"_blank\" rel=\"noopener\">hackitover.com</a>"),
    ("Academic honour","Springorum Denkmünze","Medal awarded by the Förderverein der RWTH Aachen (proRWTH) for outstanding academic achievement.","Förderverein der RWTH Aachen · July 2013 · <a href=\"http://www.prorwth.de/auszeichnen/springorum-denkmuenze/\" target=\"_blank\" rel=\"noopener\">prorwth.de</a>"),
    ("Scholarship","DFG Research Training Group scholarship","Doctoral scholarship in a DFG-funded Research Training Group (Graduiertenkolleg) in physics at RWTH Aachen University.","Deutsche Forschungsgemeinschaft (DFG) · April 2013"),
  ],
  talks_label="Talks &amp; media", talks_title="On <span>stage</span>",
  talks_intro="A selection, not a complete list: over the years I have given considerably more talks, keynotes and panel contributions than are listed here.",
  talks=[
    ("22 Sep 2026","Confex Köln","Möglichkeiten und Grenzen agentischer KI-Systeme","KI.Forum.NRW 2026 – KI.NRW annual conference","Keynote on what agentic AI systems can deliver today and where their limits are, drawing on ClaimsPilot in production.","https://www.kiforum.nrw","upcoming"),
    ("9 Jun 2026","Rome","Panel: AI and the changing insurance fraud landscape","IASIU Europe Seminar 2026","Panel with Shift, Verisk, Klang, Legentic and San Giorgio on how AI creates new fraud risks and new detection capabilities at scale.","",""),
    ("19 May 2026","Hamburg","Agentic Claims AI: Setting New Global Standards in Claims &amp; Repair Management","AWS FSI Forum Hamburg 2026","Session on ClaimsPilot's architecture on AWS and what it takes to run agentic AI at global scale.","",""),
    ("22 Apr 2026","Karlsruhe","Agentic Claims Automation: Herausforderungen und Lösungen im Versicherungsbereich","Minds Mastering Machines (M3) 2026","Field report on building an agentic AI system that automates motor claims end to end: voice-to-voice interaction, MCP, decoupled sub-agents, persistence and memory, and automated testing with LLM-based simulations.","",""),
  ],
  talks_more_title="Earlier talks",
  talks_more=[
    ("20 May 2025","Multimodale Ansätze in der KI: eine Fallstudie zur Betrugserkennung","Minds Mastering Machines (M3) 2025","Combining CLIP image embeddings, LLM text embeddings and graph models for fraud detection"),
    ("19 Mar 2024","An AI Revolution in Insurance Claim Process","NVIDIA GTC 2024, San Jose","With Andreas Decker; covered by TechTarget"),
    ("29 Nov 2023","Generative AI in the insurance industry","openGPT-X &amp; appliedAI Conference, Heilbronn","Talk and panel as OpenGPT-X industry partner"),
    ("21 Nov 2023","Wie KI die Versicherungsindustrie revolutioniert","KI Navigator 2023","End-to-end claims automation, sensor-based FNOL, fraud detection"),
    ("10 May 2023","Erkennung von Bildmanipulationen am Beispiel von Kfz-Schadenbildern","Minds Mastering Machines (M3) 2023","Deep-learning detection of manipulated and GAN/DALL-E-generated damage photos"),
    ("10 Mar 2023","A Practical Guide to AI: Moving from Pilot to Production","NVIDIA GTC Digital Spring 2023","Panel on taking AI into production"),
    ("15 May 2019","Überblick über Machine Learning","Minds Mastering Machines (M3) 2019","Introduction to classical ML methods with practical examples"),
  ],
  vol_label="Community", vol_title="Networks and <span>mentoring</span>",
  vol=[
    ("AI Frontrunner Community NRW","Member · management-level circle","KI.NRW's invitation-only circle of AI leaders at C-level and management level (Heads of AI, Directors of AI, CTOs) from North Rhine-Westphalian companies. Cross-industry exchange on best practices, experiences and how to roll AI out across an organisation.","Nov 2025 – Present"),
    ("AI Grid","Business mentor","Supporting young AI talents in turning ideas into solutions that create real value.","Jul 2024 – Present"),
    ("Connect &amp; Collect (CoCo)","Advisory board member","Advisor to an AI-based cloud initiative for interdisciplinary, networked research and innovation for the future of work.","Mar 2022 – Present"),
  ],
  contact_label="Contact", contact_title="Get in <span>touch</span>",
  contact_p="Interested in AI for insurance claims, agentic systems in production or research collaboration? Reach out on LinkedIn.",
  contact_li="Connect on LinkedIn", contact_rg="Publications on ResearchGate",
  footer="© 2026 Dr. Sebastian Schoenen · Director of Innovation &amp; Technology, ControlExpert GmbH · Head of Data &amp; AI Center of Excellence, Solvd Group",
  menu_label="Open menu",
),
"de": dict(
  lang="de", url=SITE + "de/", prefix="../",
  title="Dr. Sebastian Schoenen – KI für das Kfz-Schadenmanagement | ControlExpert & Solvd Group",
  description="Dr. Sebastian Schoenen: KI-Führungskraft für das Kfz-Schadenmanagement. Director Innovation & Technology bei ControlExpert, Leiter Data & AI CoE der Solvd Group, 75+ Data- & KI-Spezialisten.",
  og_title="Dr. Sebastian Schoenen – KI für das Kfz-Schadenmanagement",
  og_desc="Director Innovation & Technology, ControlExpert · Leiter Data & AI Center of Excellence, Solvd Group. Agentische KI, Computer Vision und GenAI für Schaden- und Reparaturmanagement.",
  nav=[("#about","Profil"),("#experience","Werdegang"),("#skills","Kompetenzen"),("#projects","Innovation"),("#talks","Vorträge"),("#volunteer","Engagement"),("#contact","Kontakt")],
  hero_tag="#AI4Claims · Region Köln/Bonn · Deutschland",
  hero_title="Director Innovation &amp; Technology bei der ControlExpert GmbH · Leiter des Data &amp; AI Center of Excellence der Solvd Group",
  hero_quote="Own the brain. Rent the body.",
  hero_badges=["Agentische KI","Computer Vision","Generative KI","InsurTech","Promovierter Physiker"],
  btn_pri="Projekte & Forschung", btn_sec="Kontakt aufnehmen",
  hero_stats=[("173+","Publikationen"),("25.5k","Zitationen"),("6","Patente"),("75+","Data- &amp; KI-Spezialisten geführt")],
  photo_alt="Porträt von Dr. Sebastian Schoenen",
  about_label="Über mich", about_title="KI-Führung. <span>Von der Strategie bis zur Produktion.</span>",
  about_p=[
    "Ich leite das Data &amp; AI Center of Excellence der Solvd Group, der Schaden- und Reparaturmanagement-Gruppe mit <strong>mehr als 200 Kunden</strong> aus Versicherungs-, Leasing- und Flottenunternehmen in <strong>46 Ländern</strong>, und bin Director Innovation &amp; Technology der ControlExpert GmbH. Das Mandat umfasst Innovation und das Data-&amp;-AI-Produktportfolio der Gruppe: eine Organisation von <strong>über 75 Data- und KI-Spezialisten</strong> in agentischer KI, Computer Vision, generativer KI und NLP, mit Budgetverantwortung für das Portfolio.",
    "Die Vision, auf die wir hinarbeiten, ist einfach: Autofahrer bekommen ihren Schaden überall am selben Tag fair ersetzt. Das Center of Excellence ist der technologische Motor dahinter. Wir entwickeln Ansätze jenseits dessen, was heutige Lösungen können, und machen daraus Kundennutzen. ClaimsPilot, unsere agentische Schadenplattform, ist bisher das sichtbarste Ergebnis.",
    "Als Gesamt-Business-Owner für Daten- und KI-Produkte verantworte ich die Entscheidungen, die bestimmen, ob das im großen Maßstab gelingt: Forschungs- und Innovationsstrategie, Make-or-Buy für KI-Produkte („Own the brain, rent the body“: die differenzierende Intelligenz gehört uns, die Infrastruktur wird gemietet), die IP-Strategie hinter sechs Patenten, MLOps und das Betriebsmodell des CoE. Plattform- und Cloud-Strategie liegen bei der IT; dort bin ich zentraler Stakeholder und richte sie an der Produktstrategie aus. KI-Governance wird zentral vom Chief Data Officer definiert und von mir umgesetzt: Responsible-AI-Regeln, Anforderungen des EU AI Act und Modellrisikomanagement für KI, die über echte Schadenfälle entscheidet.",
    "Forschung bleibt Teil der Arbeit, über ein aktives Netzwerk aus Universitäten und Instituten. Vor meiner Zeit in der Industrie habe ich selbst an der RWTH Aachen geforscht und in Astroteilchenphysik promoviert. Das prägt bis heute, wie ich führe: erst messen, dann entscheiden.",
  ],
  about_cards=[
    ("phd","Promotion in Physik","RWTH Aachen · Astroteilchenphysik · 2012–2017"),
    ("msc","M.Sc. Physik","RWTH Aachen · Hochenergie-Teilchen- und Astroteilchenphysik · 2010–2012"),
    ("work","ControlExpert GmbH / Solvd Group","Langenfeld (Rheinland) · seit 2018"),
    ("net","Forschungsnetzwerk","RWTH Aachen · TU Berlin · Bergische Universität Wuppertal · Ruhr-Universität Bochum · TU Dortmund · Fraunhofer · DFKI und weitere"),
    ("pin","Standort","Region Köln/Bonn, Deutschland"),
    ("lang","Sprachen","Deutsch (Muttersprache) · Englisch (verhandlungssicher)"),
    ("li","LinkedIn",f'<a href="{LINKEDIN}" target="_blank" rel="noopener">Profil ansehen</a>'),
  ],
  exp_label="Berufserfahrung", exp_title="Beruflicher <span>Werdegang</span>",
  exp=[
    ("Apr. 2025 – heute","Head of Data & AI Center of Excellence","Solvd Group · Hybrid",
     "Aufbau und Leitung des Data &amp; AI Center of Excellence der Gruppe: über 75 Data- und KI-Spezialisten in agentischer KI, Computer Vision, GenAI und NLP für eine Gruppe mit über 200 Versicherungs-, Leasing- und Flottenkunden in 46 Ländern. Gesamt-Business-Owner für Daten- und KI-Produkte: Produktportfolio und Budget, Forschungs- und Innovationsstrategie, Make-or-Buy- und IP-Entscheidungen, MLOps und Betriebsmodell des CoE sowie Umsetzung der gruppenweiten KI-Governance. Verantwortlich für ClaimsPilot, die agentische Schadenplattform der Gruppe, von der Strategie bis zur Produktion.",
     ["Produktportfolio","Organisationsaufbau","Budgetverantwortung","KI-Governance"]),
    ("Apr. 2023 – heute","Director Innovation & Technology","ControlExpert GmbH · Vor Ort",
     "Verantwortung für die Forschungs- und Innovationsstrategie für KI bei einem Unternehmen, das rund 20 Millionen Schadenfälle pro Jahr bearbeitet. Make-or-Buy-Entscheidungen für Kern-KI-Fähigkeiten, Steuerung der F&amp;E-Pipeline und der IP-Strategie hinter sechs Patenten, zentraler Stakeholder für die Plattform- und Cloud-Strategie der IT sowie öffentlich geförderte Forschung mit Partnern wie RWTH Aachen, Fraunhofer und Bergischer Universität Wuppertal.",
     ["Forschungs- &amp; Innovationsstrategie","Make-or-Buy","IP-Strategie","Öffentliche Forschungsförderung"]),
    ("Okt. 2020 – März 2025","Head of Research & Development","ControlExpert GmbH",
     "Leitung der F&amp;E-Abteilung und Überführung von KI-Forschung in die Produktion. Begutachtete Publikationen, Patente und angewandte Forschung zu Computer Vision und Unsicherheitsquantifizierung für Kfz-Schäden.",
     ["Deep Learning","Computer Vision","Forschungsmanagement"]),
    ("Apr. 2019 – Juni 2023","Product Manager AI Services","ControlExpert GmbH",
     "Verantwortung für das KI-Produktportfolio an der Schnittstelle von Forschung und Markt. Produktstrategie für KI-gestützte Automatisierungsservices im Schadenprozess.",
     ["KI-Produktmanagement","Schadenautomatisierung"]),
    ("Apr. 2019 – Okt. 2020","Team Leader Research and Development","ControlExpert GmbH",
     "Aufbau und Leitung des F&amp;E-Teams, aus dem später die F&amp;E-Abteilung hervorging: angewandtes Deep Learning kombiniert mit Schaden-Fachwissen.",
     ["Teamführung","Angewandte Forschung"]),
    ("Okt. 2018 – Apr. 2019","Team Leader AI Image Recognition","ControlExpert GmbH",
     "Leitung eines Data-Science-Teams für tiefe neuronale Netze zur Erkennung von Fahrzeugschäden, parallel weiterhin eigene Data-Science-Arbeit.",
     ["CNNs","Bilderkennung","Teamführung"]),
    ("Feb. 2018 – Sept. 2018","Data Scientist","ControlExpert GmbH",
     "Maschinelles Lernen auf Schadendaten; Grundlage für die automatisierten Schadenbewertungs-Pipelines.",
     ["Maschinelles Lernen","Datenanalyse"]),
    ("Feb. 2017 – Jan. 2018","Data Scientist","umlaut (vormals P3 Group) · Städteregion Aachen",
     "Data Science im industriellen Beratungsumfeld nach Abschluss der Promotion.",
     ["Data Science","Beratung"]),
    ("Okt. 2012 – Jan. 2017","Wissenschaftlicher Mitarbeiter (Doktorand)","RWTH Aachen · III. Physikalisches Institut B",
     "Promotion in der Astroteilchenphysik. Entwicklung statistischer und maschineller Lernverfahren für die Datenanalyse in der Hochenergiephysik.",
     ["Astroteilchenphysik","Statistische Modellierung","Akademische Forschung"]),
  ],
  skills_label="Kompetenzen", skills_title="Fachliche <span>Schwerpunkte</span>",
  skills=[
    ("Führung auf Managementebene",["Forschungs- &amp; Innovationsstrategie","Data-&amp;-AI-Produktportfolio","Organisationsaufbau","Budgetverantwortung","Make-or-Buy-Strategie","IP-Strategie","Umsetzung KI-Governance / EU AI Act","Kommunikation mit Geschäftsführung &amp; Stakeholdern"]),
    ("KI &amp; maschinelles Lernen",["Agentische KI","Generative KI","Deep Learning","Computer Vision","NLP / NLU","Prädiktive Modellierung","Neural Architecture Search","MLOps"]),
    ("Domänenwissen",["Schadenmanagement","InsurTech","Reparaturmanagement","Produktorientierte KI","Schadenautomatisierung","Betrugserkennung","Schadenbewertung","Kfz-Versicherung"]),
    ("Forschung &amp; Methoden",["F&amp;E-Management","Wissenschaftliches Publizieren","Datenanalyse","Mathematik","Astroteilchenphysik","Patententwicklung","Unsicherheitsquantifizierung"]),
  ],
  proj_label="Portfolio", proj_title="Wirkung &amp; <span>Innovation</span>",
  impact=[("10","KI-Produkte"),("6","Patente angemeldet / erteilt"),("10","Geförderte Forschungsprojekte"),("173+","Publikationen · 25.5k Zitationen")],
  tabs=[("products","Produkte","10"),("patents","Patente","6"),("research","Forschung","10"),("publications","Publikationen","173+"),("awards","Auszeichnungen","5")],
  flagship="Flaggschiff-Produkt", ai_product="KI-Produkt",
  products=[
    ("ClaimsPilot – agentische KI für den End-to-End-Kfz-Schadenprozess",
     "Produktive Multi-Agenten-Plattform, die den gesamten Kfz-Schadenprozess orchestriert: mehrsprachige Aufnahme per Voice, Online, Dokument und E-Mail, automatisierte Schaden- und Kostenbewertung mit Reparatur-, OEM- und Policendaten, bis zu Regulierung und Kundenkommunikation. Betrieben auf AWS. Gewinner des AI Communication Award 2026.",
     "Solvd Group / ControlExpert", True),
    ("Claims Advisor","Next-Best-Action-System in Echtzeit im FNOL-Prozess. Analysiert eingereichte Schadenfotos und Fallkontext und empfiehlt den Bearbeitungsweg: Reparatur, Ersatz oder Totalschaden.","ControlExpert GmbH", False),
    ("KI-Schadenbewertung – Bild &amp; Telematik","Kombiniert Deep Learning auf Schadenbildern mit Telematik-Sensordaten für Schweregrad-Scoring, Reparatur-/Ersatz-Entscheidungen auf Teileebene und Kostenschätzung. Rückgrat der berührungslosen Schadenbearbeitung.","ControlExpert GmbH", False),
    ("KI-Kostenbewertung","ML-Modell zur automatisierten Schätzung der Reparaturkosten auf Basis der Schadenbewertung. Datenbasierte Kosten-Benchmarks im großen Maßstab, weniger manuelle Prüfung.","ControlExpert GmbH", False),
    ("Image Fraud Prevention","KI-Bildanalyse zur Erkennung manipulierter, KI-generierter oder wiederverwendeter Schadenfotos. Findet Muster, die dem menschlichen Prüfer in großen Portfolios entgehen.","ControlExpert GmbH", False),
    ("FraudGuard AI","Hybride Betrugserkennung aus regelbasierter Logik und eigenem KI-Modell, die auffällige Schadenmuster über Dokumenten- und Bildprüfungen hinweg markiert.","ControlExpert GmbH", False),
    ("KI InvoiceCheck","Automatisierte Rechnungsprüfung für Kfz-Schäden. Gleicht Reparaturrechnungen mit Schadenbewertung, Stundensätzen und Teilepreisen ab und erkennt Überabrechnung und Widersprüche.","ControlExpert GmbH", False),
    ("Intelligent Document Processing","End-to-End-KI-Pipeline, die Informationen aus unstrukturierten Schadendokumenten wie Reparaturrechnungen, Polizeiberichten und Attesten extrahiert, klassifiziert und strukturiert.","ControlExpert GmbH", False),
    ("Voicebot für die Schadenmeldung","Konversationelle KI für die vollautomatische Erstmeldung (FNOL). Führt Anspruchsteller durch die Schadenmeldung, erfasst strukturierte Daten und stößt Workflows an.","ControlExpert GmbH", False),
    ("GenAI-basierte Haftungs- und Deckungsprüfung","Generative KI analysiert Policen, Unfallberichte und Fallfakten zur Bewertung von Haftung und Deckung. Weniger manuelle juristische Prüfung, schnellere Entscheidungen in komplexen Fällen.","ControlExpert GmbH / Solvd Group", False),
  ],
  patents=[
    ("US · EP · JP · DE","Verfahren zur Bewertung von Schäden an einem Kraftfahrzeug","KI-basiertes Verfahren zur Bewertung von Fahrzeugschäden aus Bilddateien: Schadenerkennung je Fahrzeugzone, Bestimmung des Schweregrads und Entscheidung je Teil, ob Reparatur oder Ersatz nötig ist.","US11397972B2 · EP3736758A1 · Priorität 05.03.2019 · Erteilt 26.07.2022"),
    ("DE","Automatische Erkennung von Fahrzeugschäden bei einem Unfall","Sensorbasierte Erkennung über fortlaufend erfasste Beschleunigungs-, Geschwindigkeits- und Gierratenwerte während der Fahrt.","DE102019105535A1 · Priorität 05.03.2019"),
    ("DE","Automatische Erkennung von Schadenereignissen aus Bildmaterial","Neuronales Netz erzeugt mehrere gewichtete Bounding Boxes, bildet daraus eine 2D-Dichtefunktion und nutzt sie zur Lokalisierung und Klassifikation von Schäden, jenseits der Grenzen von Non-Maximum Suppression.","DE102019129826A1 · DE102019129826B4 · Priorität 05.11.2019 · Erteilt 23.01.2025"),
    ("DE","Plausibilität eines Fahrzeug-Reparaturplans","Verfahren zur Prüfung eines Reparaturplans auf technische Plausibilität mit Bewertung, welche Teile repariert oder ersetzt werden müssen.","DE102020105545A1 · Priorität 02.03.2020"),
    ("DE","Verfahren zum Auslesen einer Fahrzeug-Identifizierungsnummer","KI-basierte Extraktion der FIN aus dem Bild eines Fahrzeugscheins oder des Fahrzeugs selbst für die automatisierte Fahrzeugidentifikation im Schadenprozess.","DE102019109941A1 · Priorität 15.04.2019"),
    ("DE","Einfache Annotation komplexer Schäden auf Bildmaterial","Verfahren auf Basis neuronaler Netze zur Annotation komplexer Schäden auf Bildern, das die Erstellung von Trainingsdaten für KI-Schadenbewertung vereinfacht.","DE102019129968A1 · Priorität 06.11.2019"),
  ],
  ongoing="Laufend", completed="Abgeschlossen", upcoming="Demnächst",
  research=[
    ("BMFTR · ErUM-Data","ErUM-ARIA",
     "Effiziente KI-Methoden für physikalische Simulationen, gemeinsam entwickelt von RWTH Aachen, FAU Erlangen-Nürnberg und ControlExpert. Die Partner bringen Simulationsprobleme aus Astroteilchenphysik, Teilchenphysik, Ingenieurwissenschaften und digitaler Schadenabwicklung ein.",
     "BMFTR · RWTH Aachen · FAU Erlangen-Nürnberg","seit 2026","ongoing"),
    ("EFRE / JFT NRW","PocketViz",
     "Mobile KI-App zur Erkennung und Vermessung von Oberflächendefekten aus multimodalen Daten (Bild, Tiefe, Text). Anwendungsfall von ControlExpert: Dellen und Kratzer an Fahrzeugkarosserien. Geleitet vom Institut TMDT der Bergischen Universität Wuppertal, weitere Anwendungspartner sind Dermanostic und Schorn.",
     "Bergische Universität Wuppertal · EFRE/JFT NRW 2021–2027","","ongoing"),
    ("EFRE / NRW","Just Scan It 3D",
     "KI-Workflow, der Smartphone-Aufnahmen in präzise 3D-Meshes und Gaussian Splats für virtuelle Schadenbewertung und AR-gestützte Besichtigung überführt.",
     "EFRE / Wirtschaftsministerium NRW","seit Sommer 2024","ongoing"),
    ("Gaia-X · BMWK","OpenGPT-X",
     "Konsortium zum Aufbau großer offener Sprachmodelle im Gaia-X-Ökosystem, mit ControlExpert als Industriepartner für die Versicherungsbranche neben Fraunhofer, Aleph Alpha, DFKI, Forschungszentrum Jülich, IONOS, TU Dresden und WDR. Ergebnisse auf der openGPT-X &amp; appliedAI Konferenz 2023 vorgestellt.",
     "Fraunhofer IAIS / IIS (Leitung) · BMWK","2022–2024","done"),
    ("BMBF","FedXtract",
     "Open-Source-SDK für föderiertes Lernen, mit dem Unternehmen KI-Modelle zur Dokumentenextraktion gemeinsam trainieren, ohne Rohdaten zu teilen, und per Transfer Learning anpassen. ControlExpert brachte den Anwendungsfall Schadendokumente und gelabelte Daten ein.",
     '<a href="https://www.fedxtract.net/" target="_blank" rel="noopener">fedxtract.net</a> · Condat AG (Koordination) · Fraunhofer IAIS · FKZ 01IS21037A',"11/2021 – 04/2024","done"),
    ("Gaia-X · BMWK","Autowerkstatt 4.0",
     "Gewinnerprojekt des Gaia-X-Förderwettbewerbs des Bundes: ein KI-basiertes Ökosystem für die Fahrzeugdiagnose, das Werkstätten, Diagnosesystemanbieter und KI-Unternehmen über Gaia-X Federated Services vernetzt.",
     "eco – Verband der Internetwirtschaft (Leitung) · BMWK","","done"),
    ("BMWK","PlanQK",
     "Plattform und Ökosystem für quantenunterstützte KI. ControlExpert ist seit 2021 assoziierter Partner und untersucht, wo quantenunterstützte KI dem Kfz-Schadenmanagement helfen kann.",
     "StoneOne AG (Leitung) · BMWK","seit 2021","done"),
    ("BMBF","HUMAINE – Kompetenzzentrum für menschzentrierte KI",
     "Kompetenzzentrum für die Metropole Ruhr, das Methoden an der Schnittstelle von KI-Entwicklung, Validierung und menschzentrierter Arbeitsgestaltung in Industrie und KMU entwickelt.",
     "BMBF / PTKA · Förderkennzeichen 02L19C200","","done"),
    ("EFRE / NRW","BIT – Bergische Innovationsplattform für KI",
     "EU- und NRW-geförderte KI-Transferplattform an der Bergischen Universität Wuppertal. ControlExpert brachte angewandte F&amp;E ein, die akademische KI-Forschung mit Automotive- und Versicherungsanwendungen verbindet.",
     "Bergische Universität Wuppertal / EFRE NRW","","done"),
    ("NRW","IT'S DIGITIVE – Sichere digitale Auftragsabwicklung für 3D-Druck",
     "NRW-gefördertes Projekt zum Aufbau eines Ersatzteil-Ökosystems für die Automobilindustrie mit sicherer digitaler Auftragsabwicklung für den produktiven Einsatz von 3D-Druck.",
     "Land Nordrhein-Westfalen","","done"),
  ],
  pub_groups=[
   ("Angewandte KI &amp; Industrie",[
    ("Springer · Mai 2024","Uncertainty estimates for semantic segmentation: providing enhanced reliability for automated motor claims handling","Meta-Klassifikationsmodell zur Bewertung der Präzision segmentierter Karosserieteile bei schlechten Fotobedingungen. AUROC 0,915; das Entfernen unsicherer Segmente hebt die mittlere IoU um 16 Prozentpunkte und senkt Fehlsegmente um 77 %.","Machine Vision and Applications · Küchler, Kröll, Schoenen, Witte"),
    ("Springer · Sept. 2024","ResBuilder: Automated learning of depth with residual structures","Neural Architecture Search, die ResNet-Architekturen von Grund auf baut, nahe am State of the Art bei geringerem Rechenaufwand. Einmal auf CIFAR-10 abgestimmte Standardparameter generalisieren auf einen proprietären Betrugserkennungsdatensatz.","ICANN 2024 · <a href=\"https://arxiv.org/abs/2308.08504\" target=\"_blank\" rel=\"noopener\">arXiv:2308.08504</a>"),
    ("IEEE/CVF WACV · Dez. 2023","Identifying label errors in object detection datasets by loss inspection","Erster Benchmark für die Erkennung von Label-Fehlern in Objektdetektionsdaten plus ein Loss-basiertes Verfahren, das alle Baselines schlägt. Findet echte Label-Fehler in öffentlichen Testdaten (Präzision bis 71,5 %) und in einem proprietären Datensatz (97 %).","Winter Conference on Applications of Computer Vision (WACV 2024)"),
    ("SIU Today · Apr. 2024","Image Fraud Prevention: Enhancing security and efficiency with image recognition for claims automation","Praxisartikel dazu, wie Computer Vision die Reparaturkostenermittlung automatisiert und zugleich Echtzeit-Betrugsprävention in den Schadenprozess einbettet, und was für den Einsatz entlang der Wertschöpfungskette nötig ist.","SIU Today – Update on Insurance Fraud"),
    ("VVW · Apr. 2023","Innovatives Schadenmanagement – Wie Technologie die Wertschöpfungskette bei Versicherungsunternehmen revolutioniert","Buchbeitrag zur technologiegetriebenen Transformation der Wertschöpfungskette im Versicherungsschaden.","In: Insurance &amp; Innovation 2023 (Hg. Andreas Eckstein) · Verlag Versicherungswirtschaft, Karlsruhe"),
    ("J. Design Research · Dez. 2022","Identification of similar design principles of passenger cars using deep neural networks","Ein auf Markenklassifikation trainiertes Netz wird per systematischer Fehleranalyse genutzt, um Fahrzeugmodelle mit ähnlichen Designprinzipien über Herstellergrenzen hinweg zu identifizieren.","Journal of Design Research, Vol. 20, No. 2"),
    ("IEEE ITSC · Okt. 2021","Fully automated, realistic license plate substitution in real-life images","CycleGAN-basiertes System, das Kennzeichen in Bildausschnitten durch beliebige Muster ersetzt und dabei Pose, Beleuchtung und Schärfe erhält, trainiert ohne Labels. Validiert über Kennzeichenerkennung, Akzeptanzstudie und FID.","Intelligent Transportation Systems Conference, Indianapolis"),
   ]),
   ("Physik – IceCube Neutrino Observatory",[
    ("Dissertation · Juli 2017","Discovery and characterization of a diffuse astrophysical muon neutrino flux with the IceCube Neutrino Observatory","Dissertation, RWTH Aachen, III. Physikalisches Institut B.","<a href=\"https://publications.rwth-aachen.de/record/696221\" target=\"_blank\" rel=\"noopener\">publications.rwth-aachen.de</a>"),
    ("Astrophysical Journal · Dez. 2016","Observation and characterization of a cosmic muon neutrino flux from the Northern Hemisphere using six years of IceCube data","Schließt einen rein atmosphärischen Ursprung der höchstenergetischen Myon-Neutrino-Ereignisse mit 5,6σ aus und charakterisiert den astrophysikalischen Fluss mit hartem Spektralindex 2,13 ± 0,13; das höchstenergetische Ereignis hat eine rekonstruierte Myonenergie von 4,5 PeV.","The Astrophysical Journal, Vol. 833, No. 1 · IceCube Collaboration"),
    ("Science · Juli 2018","Multimessenger observations of a flaring blazar coincident with high-energy neutrino IceCube-170922A","Erste Identifikation einer wahrscheinlichen Quelle hochenergetischer kosmischer Neutrinos: Das IceCube-Ereignis vom 22. September 2017 fiel mit einem Gammastrahlen-Ausbruch des Blazars TXS 0506+056 zusammen, beobachtet von 18 Teleskopen über das gesamte elektromagnetische Spektrum.","Science, Vol. 361, eaat1378 · IceCube, Fermi-LAT, MAGIC u. a."),
    ("Nature · Nov. 2017","Measurement of the multi-TeV neutrino interaction cross-section with IceCube using Earth absorption","Erste Messung des Neutrino-Nukleon-Wirkungsquerschnitts bei Energien von 6,3 bis 980 TeV, weit jenseits der Reichweite von Beschleunigern, mit der Erde selbst als Target und der Absorption aufwärts laufender Neutrinos als Observable.","Nature 551, 596–600 · IceCube Collaboration"),
    ("Nature Physics · Sept. 2018","Neutrino interferometry for high-precision tests of Lorentz symmetry with IceCube","Atmosphärische Neutrinos auf ihrem Weg durch die Erde wirken als Interferometer für die Raumzeit-Symmetrie. Die Analyse setzt einige der bis dahin schärfsten Grenzen für Lorentz-Verletzung im Neutrinosektor.","Nature Physics 14, 961–966 · IceCube Collaboration"),
    ("Eur. Phys. J. C · Juli 2014","Search for non-relativistic magnetic monopoles with IceCube","Suche nach magnetischen Monopolen aus der GUT-Ära über katalysierten Nukleonzerfall. Kein Signal; Flussgrenzen um ein bis zwei Größenordnungen verbessert, drei Größenordnungen unter der Parker-Grenze.","Eur. Phys. J. C 74:2938 · IceCube Collaboration"),
   ]),
  ],
  pub_note=f'Auswahl. Insgesamt 173 Publikationen und 25.504 Zitationen, die meisten als Autor innerhalb der IceCube Collaboration · <a href="{RESEARCHGATE}" target="_blank" rel="noopener">Vollständige Liste auf ResearchGate</a>',
  awards=[
    ("Branchenpreis · 2026","AI Communication Award 2026 – Gewinner","ClaimsPilot gewann die Kategorie „KI-Strategie, Analytics &amp; Agenten in der Kommunikation“. Die unabhängige Jury aus Wissenschaft und Wirtschaft würdigte die agentische Plattform, die den Kfz-Schadenprozess von der Erstmeldung bis zur Auszahlung orchestriert. Ich habe den Preis stellvertretend für das Team entgegengenommen.","AI Communication Award / ZIEHL-ABEGG SE · Juli 2026"),
    ("Branchenpreis · 2024","KI Innovation Award 2024 – Kategorie Heavyweight","Verliehen von F.A.Z. Institut und KI Bundesverband auf der Konferenz „Innovative Leaders“ für den KI-gestützten Schaden- und Reparaturmanagementprozess von ControlExpert.","F.A.Z. Institut · KI Bundesverband · Juli 2024"),
    ("Hackathon · 3. Platz","Talanx Insurance Hackathon","Dritter Platz beim Talanx Insurance Hackathon für angewandte KI in der Versicherung.","Talanx · April 2018 · <a href=\"https://www.hackitover.com\" target=\"_blank\" rel=\"noopener\">hackitover.com</a>"),
    ("Akademische Auszeichnung","Springorum-Denkmünze","Medaille des Fördervereins der RWTH Aachen (proRWTH) für herausragende Studienleistungen.","Förderverein der RWTH Aachen · Juli 2013 · <a href=\"http://www.prorwth.de/auszeichnen/springorum-denkmuenze/\" target=\"_blank\" rel=\"noopener\">prorwth.de</a>"),
    ("Stipendium","Stipendiat eines DFG-Graduiertenkollegs","Promotionsstipendium in einem von der DFG geförderten Graduiertenkolleg der Physik an der RWTH Aachen.","Deutsche Forschungsgemeinschaft (DFG) · April 2013"),
  ],
  talks_label="Vorträge &amp; Medien", talks_title="Auf der <span>Bühne</span>",
  talks_intro="Eine Auswahl, keine vollständige Liste: Über die Jahre habe ich deutlich mehr Vorträge, Keynotes und Panelbeiträge gehalten, als hier aufgeführt sind.",
  talks=[
    ("22. Sept. 2026","Confex Köln","Möglichkeiten und Grenzen agentischer KI-Systeme","KI.Forum.NRW 2026 – Jahrestagung von KI.NRW","Impulsvortrag dazu, was agentische KI-Systeme heute leisten und wo ihre Grenzen liegen, mit Erfahrungen aus dem Produktivbetrieb von ClaimsPilot.","https://www.kiforum.nrw","upcoming"),
    ("9. Juni 2026","Rom","Panel: KI und die veränderte Betrugslandschaft in der Versicherung","IASIU Europe Seminar 2026","Panel mit Shift, Verisk, Klang, Legentic und San Giorgio darüber, wie KI neue Betrugsrisiken und zugleich neue Erkennungsmöglichkeiten im großen Maßstab schafft.","",""),
    ("19. Mai 2026","Hamburg","Agentic Claims AI: Setting New Global Standards in Claims &amp; Repair Management","AWS FSI Forum Hamburg 2026","Session zur Architektur von ClaimsPilot auf AWS und dazu, was es braucht, agentische KI global zu betreiben.","",""),
    ("22. Apr. 2026","Karlsruhe","Agentic Claims Automation: Herausforderungen und Lösungen im Versicherungsbereich","Minds Mastering Machines (M3) 2026","Erfahrungsbericht zum Aufbau eines Agentic-AI-Systems, das Kfz-Schadenfälle End-to-End automatisiert: Voice2Voice-Interaktion, MCP, Decoupled Subagents, Persistenz und Memory sowie automatisiertes Testing mit LLM-basierten Simulationen.","",""),
  ],
  talks_more_title="Frühere Vorträge",
  talks_more=[
    ("20. Mai 2025","Multimodale Ansätze in der KI: eine Fallstudie zur Betrugserkennung","Minds Mastering Machines (M3) 2025","CLIP-Bild-Embeddings, LLM-Text-Embeddings und Graph-Modelle kombiniert für die Betrugserkennung"),
    ("19. März 2024","An AI Revolution in Insurance Claim Process","NVIDIA GTC 2024, San Jose","Mit Andreas Decker; Bericht bei TechTarget"),
    ("29. Nov. 2023","Generative KI in der Versicherungsbranche","openGPT-X &amp; appliedAI Konferenz, Heilbronn","Vortrag und Panel als OpenGPT-X-Industriepartner"),
    ("21. Nov. 2023","Wie KI die Versicherungsindustrie revolutioniert","KI Navigator 2023","End-to-End-Schadenautomatisierung, sensorbasierte Schadenmeldung, Betrugserkennung"),
    ("10. Mai 2023","Erkennung von Bildmanipulationen am Beispiel von Kfz-Schadenbildern","Minds Mastering Machines (M3) 2023","Deep-Learning-Erkennung manipulierter und GAN-/DALL-E-generierter Schadenbilder"),
    ("10. März 2023","A Practical Guide to AI: Moving from Pilot to Production","NVIDIA GTC Digital Spring 2023","Panel zur Überführung von KI in den Produktivbetrieb"),
    ("15. Mai 2019","Überblick über Machine Learning","Minds Mastering Machines (M3) 2019","Einführung in klassische ML-Verfahren an Praxisbeispielen"),
  ],
  vol_label="Engagement", vol_title="Netzwerke und <span>Mentoring</span>",
  vol=[
    ("AI Frontrunner Community NRW","Mitglied · Kreis auf Managementebene","Ausgewählter Kreis von KI.NRW mit KI-Verantwortlichen auf C-Level- und Managementebene (Head of AI, Director of AI, CTO) aus nordrhein-westfälischen Unternehmen. Branchenübergreifender Austausch zu Best Practices, Erfahrungen und der Frage, wie KI-Einsatz in der Breite eines Unternehmens gelingt.","Nov. 2025 – heute"),
    ("AI Grid","Business Mentor","Unterstützung junger KI-Talente dabei, aus Ideen Lösungen zu machen, die echten Mehrwert schaffen.","Juli 2024 – heute"),
    ("Connect &amp; Collect (CoCo)","Beiratsmitglied","Beirat einer KI-gestützten Cloud-Initiative für interdisziplinäre, vernetzte Forschung und Innovation für die Zukunftsarbeit.","März 2022 – heute"),
  ],
  contact_label="Kontakt", contact_title="Kontakt <span>aufnehmen</span>",
  contact_p="Interesse an KI im Schadenmanagement, agentischen Systemen im Produktivbetrieb oder einer Forschungskooperation? Am einfachsten über LinkedIn.",
  contact_li="Auf LinkedIn vernetzen", contact_rg="Publikationen auf ResearchGate",
  footer="© 2026 Dr. Sebastian Schoenen · Director Innovation &amp; Technology, ControlExpert GmbH · Leiter Data &amp; AI Center of Excellence, Solvd Group",
  menu_label="Menü öffnen",
),
}
